output "rds_identifier" {
  description = "RDS instance identifier."
  value       = aws_db_instance.rds.identifier
}

output "rds_endpoint" {
  description = "Private RDS endpoint for SSM-based tests."
  value       = aws_db_instance.rds.address
}

output "rds_port" {
  description = "RDS PostgreSQL port."
  value       = aws_db_instance.rds.port
}

output "rds_secret_arn" {
  description = "Secrets Manager ARN generated by RDS."
  value       = aws_db_instance.rds.master_user_secret[0].secret_arn
}

output "rds_security_group_id" {
  description = "RDS Security Group ID."
  value       = aws_security_group.rds.id
}

output "backend_security_group_id" {
  description = "Existing backend Security Group used by the foundation."
  value       = data.aws_security_group.backend.id
}

output "backend_b_source_security_group_id" {
  description = "Dedicated source SG attached only to backend-b ENIs for RDS ingress."
  value       = aws_security_group.backend_b_source.id
}
